---
- name: using handlers
  hosts: all
  become: true

  tasks:
  - name: installing httpd on redhat
    yum:
      name: httpd
      state: installed
      notify: start httpd services

  -copy:
    src: /home/ansadmin/playbooks/index.html
    dest: /var/www/html

  handlers:
    - name: start httpd services
      service:
        name: httpd
        state: started



