---
- name: implementing loops
  hosts: all
  become: true
  gather_facts: no

  tasks:
  - name: installing packages through loops
    yum:
      name: "{{ item.pkg }}"
      state: "{{ item.setup }}"
    loop:
      - { pkg: 'git', setup: 'installed' }
      - { pkg: 'make', setup: 'latest' }
      - { pkg: 'wget', setup: 'removed' }
      - { pkg: 'tree', setup: 'present' }

