---
- name: playbook to install apache tomcat
  hosts: rhelservers
  become: true
  gather_facts: yes
  vars_files:
      - tomcat_vars.yml

  tasks:
    - name: install java
      yum:
        name: java
        state: installed

    - name: downloading tomcat packages
      get_url:
        url: "{{ tomcat_url }}"
        dest: /opt
        mode: 0755
    
    - name: extracting tomcat package
      unarchive:
        src: /opt/{{ tomcat_pkg }}.tar.gz
        dest: /opt
        remote_src: yes

    - name: change the tomcat file permissions
      file:
        path: "{{ tomcat_pkg }}"
        mode: 0755
        recurse: yes

    - name: creating a link for tomcat startup.sh file
      file:
        src: /opt/{{ tomcat_pkg }}/bin/startup.sh
        dest: /usr/local/bin/tomcatup
        state: link

    - name: creating a link for tomcat shutdown.sh file
      file:
        src: /opt/{{ tomcat_pkg }}/bin/shutdown.sh
        dest: /usr/local/bin/tomcatdown
        state: link

    - name: start the services
      command: ./startup.sh
      args:
        chdir: /opt/{{ tomcat_pkg}}/bin
